name: windows-vs2019

on:
  workflow_dispatch:

jobs:
  windows-vs2019:
    runs-on: windows-2019

    env:
      NCNN_VERSION: 20210720
      CPU_PKG_NAME: ncnn-20210720-windows-vs2019
      GPU_PKG_NAME: ncnn-20210720-windows-vs2019-vulkan

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 检出ncnn
      - name: checkout ncnn
        uses: actions/checkout@v2
        with:
          repository: Tencent/ncnn
          path: ncnn-${{ env.NCNN_VERSION }}
          ref: ${{ env.NCNN_VERSION }}
          submodules: recursive

      # 安装vulkan
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.162.0/windows/VulkanSDK-1.2.162.0-Installer.exe?Human=true -OutFile VulkanSDK-1.2.162.0-Installer.exe
          7z x -aoa ./VulkanSDK-1.2.162.0-Installer.exe -oVulkanSDK
          Remove-Item .\VulkanSDK\Demos, .\VulkanSDK\Samples, .\VulkanSDK\Third-Party, .\VulkanSDK\Tools, .\VulkanSDK\Tools32 -Recurse

      # 缓存vulkan
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1.0.3
        with:
          path: "VulkanSDK"
          key: VulkanSDK-1.2.162.0-Installer

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-ncnn-cpu-vs2019.bat ncnn-${{ env.NCNN_VERSION }}
          cp build-ncnn-gpu-vs2019.bat ncnn-${{ env.NCNN_VERSION }}
          cp ncnn_cmake_options.txt ncnn-${{ env.NCNN_VERSION }}

      # 编译ncnn cpu
      - name: build cpu
        run: |
          cd ncnn-${{ env.NCNN_VERSION }}
          ./build-ncnn-cpu-vs2019.bat

      # install文件夹改名，并使用7z压缩
      - name: 7zip
        run: |
          mv ncnn-${{ env.NCNN_VERSION }}/build-v142-x64-cpu/install windows-x64
          mv ncnn-${{ env.NCNN_VERSION }}/build-v142-Win32-cpu/install windows-x86
          7z a ${{ env.CPU_PKG_NAME }}.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CPU_PKG_NAME }}
          path: ${{ env.CPU_PKG_NAME }}.7z

      # 编译ncnn gpu
      - name: build gpu
        run: |
          $env:VULKAN_SDK="$(pwd)/VulkanSDK"
          cd ncnn-${{ env.NCNN_VERSION }}
          ./build-ncnn-gpu-vs2019.bat

      # install文件夹改名，并使用7z压缩
      - name: 7zip
        run: |
          mv ncnn-${{ env.NCNN_VERSION }}/build-v142-x64-gpu/install windows-x64
          mv ncnn-${{ env.NCNN_VERSION }}/build-v142-Win32-gpu/install windows-x86
          7z a ${{ env.GPU_PKG_NAME }}.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.GPU_PKG_NAME }}
          path: ${{ env.GPU_PKG_NAME }}.7z