name: windows-vs2019

on:
  workflow_dispatch:

jobs:
  windows-vs2019:
    runs-on: windows-2019

    env:
      NCNN_VERSION: 20210322
      CPU_PKG_NAME: ncnn-20210322-windows-vs2019

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 检出ncnn
      - name: checkout ncnn
        uses: actions/checkout@v2
        with:
          repository: Tencent/ncnn
          path: ncnn-${{ env.NCNN_VERSION }}
          ref: ${{ env.NCNN_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-ncnn-cpu-vs2019.bat ncnn-${{ env.NCNN_VERSION }}
          cp ncnn_cmake_options.txt ncnn-${{ env.NCNN_VERSION }}

      # 编译ncnn
      - name: build
        run: |
          cd ncnn-${{ env.NCNN_VERSION }}
          ./build-ncnn-cpu-vs2019.bat

      # install文件夹改名，并使用7z压缩
      - name: rename
        run: |
          mv ncnn-${{ env.NCNN_VERSION }}/build-v142-x64/install windows-x64
          mv ncnn-${{ env.NCNN_VERSION }}/build-v142-Win32/install windows-x86
          7z a ${{ env.CPU_PKG_NAME }}.7z windows-x64 windows-x86

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CPU_PKG_NAME }}
          path: |
            ${{ env.CPU_PKG_NAME }}.7z